### ISSUE TITLE
Unable to execute prepare_data.py

### ISSUE THREAD

**Issue by s58vshar** [KeyuWu-CS/MonoHair#4]
I tried to run the script but I ran into the following error 

loading configs/reconstruct/base.yaml...
loading configs/reconstruct/short_curly1.yaml...
* HairGenerate:
   * connect_dot_threshold: 0.8
   * connect_scalp: True
   * connect_segments: True
   * connect_threshold: 0.0025
   * connect_to_guide: None
   * dist_to_root: 6
   * generate_segments: True
   * grow_threshold: 0.85
   * out_ratio: 0.0
* PMVO:
   * conf_threshold: 0.1
   * filter_point: True
   * genrate_ori_only: None
   * infer_inner: True
   * num_sample_per_grid: 6
   * optimize: True
   * patch_size: 5
   * threshold: 0.05
   * visible_threshold: 1
* bbox_min: [-0.32, -0.32, -0.24]
* bust_to_origin: [0.006, -1.644, 0.01]
* camera_path: camera/calib_data/wky07-22/cam_params.json
* check_strands: True
* cpu: None
* data:
   * Conf_path: conf
   * Occ3D_path: ours/Occ3D.mat
   * Ori2D_path: best_ori
   * Ori3D_path: ours/Ori3D.mat
   * bust_path: ours/bust_long_tsfm.obj
   * case: short_curly1
   * depth_path: render_depth
   * frame_interval: 7
   * image_size: [1080, 1920]
   * mask_path: hair_mask
   * raw_points_path: ours/colmap_points.obj
   * root: data
   * scalp_path: ours/scalp_tsfm.obj
   * strands_path: ours/world_str_raw.dat
* device: cuda:0
* gpu: 0
* image_camera_path: ours/cam_params.json
* infer_inner:
   * render_data: True
   * run_mvs: True
* name: 10-16
* ngp:
   * marching_cubes_density_thresh: 3.0
* output_root: output
* prepare_data:
   * fit_bust: None
   * process_bust: True
   * process_camera: True
   * process_imgs: True
   * render_depth: True
   * run_ngp: True
   * select_images: True
* save_path: refine
* scalp_diffusion: None
* seed: 0
* segment:
   * CDGNET_ckpt: assets/CDGNet/LIP_epoch_149.pth
   * MODNET_ckpt: assets/MODNet/modnet_photographic_portrait_matting.ckpt
   * scene_path: None
* vsize: 0.005
* yaml: configs/reconstruct/short_curly1
existing options file found (identical)
distance: 2.254131284488828
distance: 2.254131284488828
16:11:36 SUCCESS  Initialized CUDA 11.5. Active GPU is #0: NVIDIA GeForce RTX 3090 [86]
16:11:36 INFO     Loading NeRF dataset from
16:11:36 WARNING    data/short_curly1/colmap/cam_params.json does not contain any frames. Skipping.
16:11:36 INFO       data/short_curly1/colmap/transforms.json
16:11:36 WARNING    data/short_curly1/colmap/base_cam.json does not contain any frames. Skipping.
16:11:36 WARNING    data/short_curly1/colmap/key_frame.json does not contain any frames. Skipping.
16:11:36 WARNING    data/short_curly1/colmap/base_transform.json does not contain any frames. Skipping.
16:11:37 SUCCESS  Loaded 409 images after 0s
16:11:37 INFO       cam_aabb=[min=[-0.820552,-0.696267,0.88122], max=[3.15477,1.71274,1.34521]]
16:11:37 INFO     Loading network snapshot from: data/short_curly1/colmap/base.ingp
16:11:38 INFO     GridEncoding:  Nmin=16 b=3.28134 F=4 T=2^19 L=8
16:11:38 INFO     Density model: 3--[HashGrid]-->32--[FullyFusedMLP(neurons=64,layers=3)]-->1
16:11:38 INFO     Color model:   3--[Composite]-->16+16--[FullyFusedMLP(neurons=64,layers=4)]-->3
16:11:38 INFO       total_encoding_params=13194816 total_network_params=10240
Screenshot transforms from  data/short_curly1/colmap/base_transform.json
Generating mesh via marching cubes and saving to data/short_curly1/colmap/base.obj. Resolution=[512,512,512], Density Threshold=3.0
16:11:38 INFO     #vertices=6031894 #triangles=11994368
range(0, 16)
rendering data/short_curly1/trainning_images/capture_images/000.png
rendering data/short_curly1/trainning_images/capture_images/001.png
rendering data/short_curly1/trainning_images/capture_images/002.png
rendering data/short_curly1/trainning_images/capture_images/003.png
rendering data/short_curly1/trainning_images/capture_images/004.png
rendering data/short_curly1/trainning_images/capture_images/005.png
rendering data/short_curly1/trainning_images/capture_images/006.png
rendering data/short_curly1/trainning_images/capture_images/007.png
rendering data/short_curly1/trainning_images/capture_images/008.png
rendering data/short_curly1/trainning_images/capture_images/009.png
rendering data/short_curly1/trainning_images/capture_images/010.png
rendering data/short_curly1/trainning_images/capture_images/011.png
rendering data/short_curly1/trainning_images/capture_images/012.png
rendering data/short_curly1/trainning_images/capture_images/013.png
rendering data/short_curly1/trainning_images/capture_images/014.png
rendering data/short_curly1/trainning_images/capture_images/015.png
unable to load materials from: material.mtl
Start calculating masks!
100%|
Start calculating hair masks!
Traceback (most recent call last):
  File "/home/sharma/MonoHair/prepare_data.py", line 182, in <module>
    calculate_mask(segment_args)
  File "/home/sharma/MonoHair/preprocess_capture_data/calc_masks.py", line 171, in calculate_mask
    for key, nkey in zip(state_dict_old.keys(), state_dict.keys()):
RuntimeError: OrderedDict mutated during iteration

**Comment by s58vshar** [comment]
I am trying to run the script for my own video, and I copied missing files from the provided data.

**Comment by banglevan** [comment]
Could you share me the script to run my own video, I'm have some issues that yours

**Comment by 0mil** [comment]
@s58vshar 
I think you are experiencing the same issue as I did. Please refer to #5 👍

**Comment by s58vshar** [comment]
@0mil Thank you! It was the same issue indeed.

**Comment by s58vshar** [comment]
@banglevan the script is already present in github repo under video_preprocess folder.
